<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InfluxDB.Client" Version="5.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DanaTadbir.I4Twins.SensorData.Domain\DanaTadbir.I4Twins.SensorData.Domain.csproj" />
  </ItemGroup>

</Project>
